Update main_fashionhub.yml
edfs

diff --git a/.github/workflows/main_fashionhub.yml b/.github/workflows/main_fashionhub.yml
--- a/.github/workflows/main_fashionhub.yml
+++ b/.github/workflows/main_fashionhub.yml
@@ -1,6 +1,3 @@
-# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
-# More GitHub Actions for Azure: https://github.com/Azure/actions
-
 name: Build and deploy Node.js app to Azure Web App - FashionHub
 
 on:
@@ -13,7 +10,7 @@ jobs:
   build:
     runs-on: ubuntu-latest
     permissions:
-      contents: read #This is required for actions/checkout
+      contents: read
 
     steps:
       - uses: actions/checkout@v4
@@ -26,9 +23,10 @@ jobs:
       - name: npm install and fix dependencies
         run: |
           npm install
-          npm install @vitejs/plugin-react-swc@3.5.0 --save-dev  # Cài đặt phiên bản cụ thể
+          npm install @vitejs/plugin-react-swc@3.5.0 --save-dev
+          npm audit fix
           echo "Running vite build..."
-          CI=false vite build || { echo "Vite build failed"; exit 1; }
+          CI=false npx vite build --mode production || { echo "Vite build failed"; exit 1; }
           ls -la  # Debug: Kiểm tra thư mục dist có tồn tại
           if [ ! -d "dist/" ]; then echo "Error: dist/ directory not found"; exit 1; fi
 
@@ -42,8 +40,8 @@ jobs:
     runs-on: ubuntu-latest
     needs: build
     permissions:
-      id-token: write #This is required for requesting the JWT
-      contents: read #This is required for actions/checkout
+      id-token: write
+      contents: read
 
     steps:
       - name: Download artifact from build job
